---
name: Pipeline - Auto Sync

on:
  workflow_dispatch:
<<<<<<< HEAD:.github/workflows/auto-sync.yml
=======
  
  schedule:
    - cron: '0 0 * * *'
>>>>>>> 8cdd16e48e8e5ea4a03261173766f849200e20f2:.github/Flux de travail/auto-sync.yml

jobs:
  build:
    name: Auto Sync
    runs-on: ubuntu-latest
    steps:
    # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      # More info: https://github.com/peter-murray/workflow-application-token-action.
      - name: Get token
        id: get_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.ID_AUTOSYNCBOT }}
          application_private_key: ${{ secrets.PEM_AUTOSYNCBOT }}

      # More info: https://github.com/actions/checkout.
      - name: Checkout & Authentication
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          token: ${{ steps.get_token.outputs.token }}
          persist-credentials: false

      # More info: https://github.com/vesoft-inc/auto-sync-repos.
      - name: Auto Sync
        uses: vesoft-inc/auto-sync-repos@7d5c7dbca16b4b64fb7668b64fb81337f2daa1a2
        with:
          from_repo: 1Password/1password-teams-open-source
          repo_token: ${{ steps.get_token.outputs.token }}
